<?php

declare(strict_types=1);
namespace Acme\Jobs\Rest;

/**
 * WPKernel extension shim.
 * Edits to this file will be preserved during apply operations.
 */
if (!class_exists(Acme\Jobs\Generated\Rest\JobCategoryController::class)) {
    require_once(__DIR__ . '/../../.generated/php/Rest/JobCategoryController.php');
}
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Source: wpk.config.ts → resources.jobCategory
 * Schema: auto:jobCategory (auto)
 */
class JobCategoryController extends Acme\Jobs\Generated\Rest\JobCategoryController
{
}
