import path from 'node:path';

export interface RegistrarModuleFactoryOptions {
	readonly outputDir: string;
	readonly source?: string;
}

export interface RegistrarModuleMetadata {
	readonly filePath: string;
	readonly banner: readonly string[];
	readonly registrationFunction: string;
	readonly settingsHelper: string;
}

export function buildAutoRegisterModuleMetadata({
	outputDir,
	source,
}: RegistrarModuleFactoryOptions): RegistrarModuleMetadata {
	const bannerSource = source ?? 'project config';
	return {
		filePath: path.join(outputDir, 'auto-register.ts'),
		banner: [
			'/**',
			' * AUTO-GENERATED by WPKernel CLI.',
			` * Source: ${bannerSource} → blocks.jsOnly`,
			' */',
		],
		registrationFunction: 'registerGeneratedBlocks',
		settingsHelper: 'createGeneratedBlockSettings',
	};
}

export function generateBlockImportPath(
	blockPath: string,
	outputPath: string
): string {
	const relativePath = path.relative(path.dirname(outputPath), blockPath);
	const normalised = relativePath.split(path.sep).join('/');

	if (!normalised.startsWith('.')) {
		return `./${normalised}`;
	}

	return normalised;
}
