<?php

/**
 * Plugin Name: Acme Jobs
 * Description: Bootstrap loader for the Acme Jobs WPKernel integration.
 * Version: 0.1.0
 * Requires at least: 6.7
 * Requires PHP: 8.1
 * Text Domain: acme-jobs
 * Author: WPKernel Contributors
 * Author URI: https://github.com/wpkernel/wpkernel
 * License: GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Generated by WPKernel CLI - edits between WPK:BEGIN AUTO and WPK:END AUTO are managed by the generator.
 * Source: wpk.config.ts → plugin/loader
 * @package AcmeJobs
 */
declare(strict_types=1);
namespace Acme\Jobs;

/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → plugin/loader
 */
// WPK:BEGIN AUTO
if (!defined('ABSPATH')) {
    exit();
}
/**
 * Retrieve WPKernel REST controllers generated for this plugin.
 * @return array<int, object>
 */
function get_wpkernel_controllers(): array
{
    return [new \Acme\Jobs\Generated\Rest\JobController()];
}
/** Register WPKernel REST controllers with WordPress. */
function register_wpkernel_routes(): void
{
    $controllers = get_wpkernel_controllers();
    foreach ($controllers as $controller) {
        if (!method_exists($controller, 'register_routes')) {
            continue;
        }
        $controller->register_routes();
    }
}
/** Attach wpk hooks required for REST registration. */
function bootstrap_kernel(): void
{
    add_action('rest_api_init', __NAMESPACE__ . '\register_wpkernel_routes');
}
bootstrap_kernel();
// WPK:END AUTO
