<?php
declare(strict_types=1);

/**
 * AUTO-GENERATED by WP Kernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → php/index
 */

return [
    "WP\Kernel\Showcase\Rest\BaseController" =>
        __DIR__ . "/Rest/BaseController.php",
    "WP\Kernel\Showcase\Policy\Policy" => __DIR__ . "/Policy/Policy.php",
    "WP\Kernel\Showcase\Rest\JobController" =>
        __DIR__ . "/Rest/JobController.php",
    "WP\Kernel\Showcase\Registration\PersistenceRegistry" =>
        __DIR__ . "/Registration/PersistenceRegistry.php",
];
