<?php
declare(strict_types=1);

/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources (storage + identity metadata)
 */

namespace WPKernel\Showcase\Registration;

// WPK:BEGIN AUTO
final class PersistenceRegistry
{
    public static function get_config(): array
    {
        return [
            "resources" => [
                "job" => [
                    "identity" => [
                        "param" => "id",
                        "type" => "number",
                    ],
                    "storage" => [
                        "meta" => [
                            "apply_deadline" => [
                                "single" => true,
                                "type" => "string",
                            ],
                            "department" => [
                                "single" => true,
                                "type" => "string",
                            ],
                            "job_type" => [
                                "single" => true,
                                "type" => "string",
                            ],
                            "location" => [
                                "single" => true,
                                "type" => "string",
                            ],
                            "remote_capability" => [
                                "single" => true,
                                "type" => "string",
                            ],
                            "salary_max" => [
                                "single" => true,
                                "type" => "integer",
                            ],
                            "salary_min" => [
                                "single" => true,
                                "type" => "integer",
                            ],
                            "seniority" => [
                                "single" => true,
                                "type" => "string",
                            ],
                        ],
                        "mode" => "wp-post",
                        "postType" => "wpk_job",
                        "statuses" => ["closed"],
                        "supports" => ["title", "editor", "custom-fields"],
                        "taxonomies" => [
                            "department" => [
                                "hierarchical" => false,
                                "taxonomy" => "wpk_job_department",
                            ],
                            "location" => [
                                "hierarchical" => false,
                                "taxonomy" => "wpk_job_location",
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
}
// WPK:END AUTO
