/**
 * AUTO-GENERATED by WPKernel CLI.
 * Source: wpk.config.ts → blocks.jsOnly
 */
export function registerGeneratedBlocks() {
	// No JS-only blocks require auto-registration.
}

registerGeneratedBlocks();
