<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources.application
 * Schema: application (manual)
 * Route: [GET] /acme/v1/applications
 * Route: [GET] /acme/v1/applications/:uuid
 * Route: [PATCH] /acme/v1/applications/:uuid
 * Route: [POST] /acme/v1/applications
 */
namespace Acme\Jobs\Generated\Rest;

use Acme\Jobs\Generated\Capability\Capability;
use WP_Error;
use WP_Post;
use WP_Query;
use WP_REST_Request;
use function is_wp_error;
// WPK:BEGIN AUTO
final class ApplicationController extends BaseController
{
    public function get_resource_name(): string
    {
        return 'application';
    }
    public function get_schema_key(): string
    {
        return 'application';
    }
    public function get_rest_args(): array
    {
        return ['candidate_email' => ['required' => true, 'schema' => ['format' => 'email', 'type' => 'string']], 'candidate_name' => ['required' => true, 'schema' => ['type' => 'string']], 'created_at' => ['required' => true, 'schema' => ['format' => 'date-time', 'type' => 'string']], 'job_id' => ['required' => true, 'schema' => ['type' => 'integer']], 'resume_url' => ['schema' => ['format' => 'uri', 'type' => 'string']], 'status' => ['description' => 'Filter applications by status.', 'required' => true, 'schema' => ['enum' => ['new', 'screening', 'interview', 'offer', 'rejected'], 'type' => 'string']], 'updated_at' => ['schema' => ['format' => 'date-time', 'type' => 'string']], 'uuid' => ['identity' => ['param' => 'uuid', 'type' => 'string'], 'required' => true, 'schema' => ['format' => 'uuid', 'type' => 'string']]];
    }
    /**
     * Handle [GET] /acme/v1/applications.
     * @wp-kernel route-kind list
     */
    public function getAcmeV1Applications(WP_REST_Request $request)
    {
        $permission = Capability::enforce('application.list', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $post_type = $this->getApplicationPostType();
        $per_page = (int) $request->get_param('per_page');
        if ($per_page <= 0) {
            $per_page = 10;
        }
        if ($per_page > 100) {
            $per_page = 100;
        }
        
        $statuses = $this->getApplicationStatuses();
        
        $query_args = ['post_type' => $post_type, 'post_status' => $statuses, 'fields' => 'ids', 'paged' => max(1, (int) $request->get_param('page')), 'posts_per_page' => $per_page];
        
        $meta_query = [];
        $job_idMeta = $request->get_param('job_id');
        if ($job_idMeta !== null) {
            $job_idMeta = match (is_scalar($job_idMeta)) {
                true => trim((string) $job_idMeta),
                default => null,
            };
            if ($job_idMeta !== null && $job_idMeta !== '') {
                $meta_query[] = ['key' => 'job_id', 'compare' => '=', 'value' => $job_idMeta];
            }
        }
        $cv_attachment_idMeta = $request->get_param('cv_attachment_id');
        if ($cv_attachment_idMeta !== null) {
            $cv_attachment_idMeta = match (is_scalar($cv_attachment_idMeta)) {
                true => trim((string) $cv_attachment_idMeta),
                default => null,
            };
            if ($cv_attachment_idMeta !== null && $cv_attachment_idMeta !== '') {
                $meta_query[] = ['key' => 'cv_attachment_id', 'compare' => '=', 'value' => $cv_attachment_idMeta];
            }
        }
        $statusMeta = $request->get_param('status');
        if ($statusMeta !== null) {
            $statusMeta = match (is_scalar($statusMeta)) {
                true => trim((string) $statusMeta),
                default => null,
            };
            if ($statusMeta !== null && $statusMeta !== '') {
                $meta_query[] = ['key' => 'status', 'compare' => '=', 'value' => $statusMeta];
            }
        }
        if (count($meta_query) > 0) {
            $query_args['meta_query'] = $meta_query;
        }
        
        $query = new WP_Query($query_args);
        
        $items = [];
        
        foreach ($query->posts as $post_id) {
            $post = get_post($post_id);
            if (!$post instanceof WP_Post) {
                continue;
            }
            $items[] = $this->prepareApplicationResponse($post, $request);
        }
        
        return ['items' => $items, 'total' => (int) $query->found_posts, 'pages' => (int) $query->max_num_pages];
    }
    /**
     * Handle [GET] /acme/v1/applications/:uuid.
     * @wp-kernel route-kind get
     */
    public function getAcmeV1ApplicationsUuid(WP_REST_Request $request)
    {
        $uuid = $request->get_param('uuid');
        
        $permission = Capability::enforce('application.get', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        if (!is_string($uuid) || '' === trim($uuid)) {
            return new WP_Error('wpk_application_missing_identifier', 'Missing identifier for Application.', ['status' => 400]);
        }
        $uuid = trim((string) $uuid);
        
        $post = $this->resolveApplicationPost($uuid);
        if (!$post instanceof WP_Post) {
            return new WP_Error('wpk_application_not_found', 'Application not found.', ['status' => 404]);
        }
        
        return $this->prepareApplicationResponse($post, $request);
    }
    /**
     * Handle [PATCH] /acme/v1/applications/:uuid.
     * @wp-kernel route-kind update
     * @wp-kernel resource.wpPost.mutation update
     */
    public function patchAcmeV1ApplicationsUuid(WP_REST_Request $request)
    {
        $uuid = $request->get_param('uuid');
        
        $permission = Capability::enforce('application.update', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $uuid = $request->get_param('uuid');
        if (!is_string($uuid) || '' === trim($uuid)) {
            return new WP_Error('wpk_application_missing_identifier', 'Missing identifier for Application.', ['status' => 400]);
        }
        $uuid = trim((string) $uuid);
        $post = $this->resolveApplicationPost($uuid);
        if (!$post instanceof WP_Post) {
            return new WP_Error('wpk_application_not_found', 'Application not found.', ['status' => 404]);
        }
        $post_data = ['ID' => $post->ID, 'post_type' => $this->getApplicationPostType()];
        // @wp-kernel resource.wpPost.mutation status-validation
        // @wp-kernel mutation:status normalise
        $status = $request->get_param('status');
        if (null !== $status) {
            $post_data['post_status'] = $this->normaliseApplicationStatus($status);
        }
        $result = wp_update_post($post_data, true);
        if (is_wp_error($result)) {
            return $result;
        }
        if (0 === $result) {
            return new WP_Error('wpk_application_update_failed', 'Unable to update Application.', ['status' => 500]);
        }
        // @wp-kernel resource.wpPost.mutation sync-meta
        // @wp-kernel mutation:meta update
        $this->syncApplicationMeta($post->ID, $request);
        // @wp-kernel resource.wpPost.mutation sync-taxonomies
        // @wp-kernel mutation:taxonomies update
        $taxonomy_result = $this->syncApplicationTaxonomies($post->ID, $request);
        if (is_wp_error($taxonomy_result)) {
            return $taxonomy_result;
        }
        // @wp-kernel resource.wpPost.mutation cache-priming
        // @wp-kernel mutation:cache prime
        // @wp-kernel cache:wp-post prime
        $updated = get_post($post->ID);
        if (!$updated instanceof WP_Post) {
            return new WP_Error('wpk_application_load_failed', 'Unable to load updated Application.', ['status' => 500]);
        }
        return $this->prepareApplicationResponse($updated, $request);
    }
    /**
     * Handle [POST] /acme/v1/applications.
     * @wp-kernel route-kind create
     * @wp-kernel resource.wpPost.mutation create
     */
    public function postAcmeV1Applications(WP_REST_Request $request)
    {
        $permission = Capability::enforce('application.create', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $post_type = $this->getApplicationPostType();
        $post_data = ['post_type' => $post_type];
        // @wp-kernel resource.wpPost.mutation status-validation
        // @wp-kernel mutation:status normalise
        $status = $request->get_param('status');
        $post_data['post_status'] = $this->normaliseApplicationStatus($status);
        $post_id = wp_insert_post($post_data, true);
        if (is_wp_error($post_id)) {
            return $post_id;
        }
        if (0 === $post_id) {
            return new WP_Error('wpk_application_create_failed', 'Unable to create Application.', ['status' => 500]);
        }
        // @wp-kernel resource.wpPost.mutation sync-meta
        // @wp-kernel mutation:meta update
        $this->syncApplicationMeta($post_id, $request);
        // @wp-kernel resource.wpPost.mutation sync-taxonomies
        // @wp-kernel mutation:taxonomies update
        $taxonomy_result = $this->syncApplicationTaxonomies($post_id, $request);
        if (is_wp_error($taxonomy_result)) {
            return $taxonomy_result;
        }
        // @wp-kernel resource.wpPost.mutation cache-priming
        // @wp-kernel mutation:cache prime
        // @wp-kernel cache:wp-post prime
        $post = get_post($post_id);
        if (!$post instanceof WP_Post) {
            return new WP_Error('wpk_application_load_failed', 'Unable to load created Application.', ['status' => 500]);
        }
        return $this->prepareApplicationResponse($post, $request);
    }
    private function syncApplicationMeta(int $post_id, WP_REST_Request $request): void
    {
        $job_idMeta = $request->get_param('job_id');
        if (null !== $job_idMeta) {
            $job_idMeta = is_numeric($job_idMeta) ? (double) $job_idMeta : 0.0;
            update_post_meta($post_id, 'job_id', $job_idMeta);
        }
        $cv_attachment_idMeta = $request->get_param('cv_attachment_id');
        if (null !== $cv_attachment_idMeta) {
            $cv_attachment_idMeta = is_numeric($cv_attachment_idMeta) ? (double) $cv_attachment_idMeta : 0.0;
            update_post_meta($post_id, 'cv_attachment_id', $cv_attachment_idMeta);
        }
        $statusMeta = $request->get_param('status');
        if (null !== $statusMeta) {
            $statusMeta = is_string($statusMeta) ? $statusMeta : (string) $statusMeta;
            update_post_meta($post_id, 'status', $statusMeta);
        }
    }
    private function syncApplicationTaxonomies(int $post_id, WP_REST_Request $request)
    {
        unset($post_id, $request);
        return true;
    }
    private function prepareApplicationResponse(WP_Post $post, WP_REST_Request $request): array
    {
        $data = ['id' => (int) $post->ID, 'status' => (string) $post->post_status];
        $data['meta'] = get_post_meta($post->ID);
        $job_idMeta = get_post_meta($post->ID, 'job_id', true);
        $job_idMeta = is_numeric($job_idMeta) ? (double) $job_idMeta : 0.0;
        $data['job_id'] = $job_idMeta;
        $cv_attachment_idMeta = get_post_meta($post->ID, 'cv_attachment_id', true);
        $cv_attachment_idMeta = is_numeric($cv_attachment_idMeta) ? (double) $cv_attachment_idMeta : 0.0;
        $data['cv_attachment_id'] = $cv_attachment_idMeta;
        $statusMeta = get_post_meta($post->ID, 'status', true);
        $statusMeta = is_string($statusMeta) ? $statusMeta : (string) $statusMeta;
        $data['status'] = $statusMeta;
        return $data;
    }
}
// WPK:END AUTO
