<?php
declare(strict_types=1);

/**
 * AUTO-GENERATED by WP Kernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: kernel.config.ts → resources (namespace: wp-kernel-showcase)
 */

namespace WP\Kernel\Showcase\Rest;

// WPK:BEGIN AUTO
abstract class BaseController
{
    public function get_namespace(): string
    {
        return "wp-kernel-showcase";
    }
}
// WPK:END AUTO
