<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources (namespace: acme-jobs)
 */
namespace Acme\Jobs\Generated\Rest;

// WPK:BEGIN AUTO
abstract class BaseController
{
    public function get_namespace(): string
    {
        return 'acme-jobs';
    }
}
// WPK:END AUTO
