<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources.jobCategory
 * Schema: auto:jobCategory (auto)
 * Route: [GET] /acme/v1/job-categories
 * Route: [GET] /acme/v1/job-categories/:id
 */
namespace Acme\Jobs\Generated\Rest;

use Acme\Jobs\Generated\Capability\Capability;
use WP_Error;
use WP_REST_Request;
use WP_Term;
use WP_Term_Query;
use function is_wp_error;
// WPK:BEGIN AUTO
final class JobCategoryController extends BaseController
{
    public function get_resource_name(): string
    {
        return 'jobCategory';
    }
    public function get_schema_key(): string
    {
        return 'auto:jobCategory';
    }
    public function get_rest_args(): array
    {
        return [];
    }
    /**
     * Handle [GET] /acme/v1/job-categories.
     * @wp-kernel route-kind list
     */
    public function getAcmeV1JobCategories(WP_REST_Request $request)
    {
        $permission = Capability::enforce('jobCategory.list', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $taxonomy = $this->getJobCategoryTaxonomy();
        
        $per_page = (int) $request->get_param('per_page');
        if ($per_page <= 0) {
            $per_page = 10;
        }
        if ($per_page > 100) {
            $per_page = 100;
        }
        
        $page = (int) $request->get_param('page');
        if ($page <= 0) {
            $page = 1;
        }
        
        $query_args = ['taxonomy' => $taxonomy, 'hide_empty' => false];
        
        $extra_args = $request->get_params();
        foreach ($extra_args as $key => $value) {
            if (in_array($key, ['page', 'per_page', 'taxonomy', 'hide_empty'], true)) {
                continue;
            }
            $query_args[$key] = $value;
        }
        
        $query_args['number'] = $per_page;
        $query_args['offset'] = ($page - 1) * $per_page;
        
        $term_query = new WP_Term_Query($query_args);
        
        $results = $term_query->query($query_args);
        if (is_wp_error($results)) {
            return $results;
        }
        
        $items = [];
        
        foreach ($results as $term) {
            if ($term instanceof WP_Term) {
                $items[] = $this->prepareJobCategoryTermResponse($term);
            }
        }
        
        $count_query_args = $query_args;
        
        $count_query_args['count'] = true;
        $count_query_args['number'] = 0;
        $count_query_args['offset'] = 0;
        
        $count_query = new WP_Term_Query($count_query_args);
        
        $total = (int) $count_query->query($count_query_args);
        
        $pages = (int) ceil($total / max(1, $per_page));
        
        return ['items' => $items, 'total' => $total, 'pages' => $pages];
    }
    /**
     * Handle [GET] /acme/v1/job-categories/:id.
     * @wp-kernel route-kind get
     */
    public function getAcmeV1JobCategoriesId(WP_REST_Request $request)
    {
        $id = (int) $request->get_param('id');
        
        $permission = Capability::enforce('jobCategory.get', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $identity = $this->validateJobCategoryIdentity($request->get_param('id'));
        if (is_wp_error($identity)) {
            return $identity;
        }
        
        $term = $this->resolveJobCategoryTerm($identity);
        
        if (!$term instanceof WP_Term) {
            return new WP_Error('wpk_job_category_not_found', 'Unable to locate JobCategory term.', ['status' => 404]);
        }
        
        return $this->prepareJobCategoryTermResponse($term);
    }
    private function getJobCategoryTaxonomy(): string
    {
        return 'acme_job_category';
    }
    private function prepareJobCategoryTermResponse(WP_Term $term): array
    {
        return ['id' => (int) $term->term_id, 'slug' => (string) $term->slug, 'name' => (string) $term->name, 'taxonomy' => (string) $term->taxonomy, 'hierarchical' => true, 'description' => (string) $term->description, 'parent' => (int) $term->parent, 'count' => (int) $term->count];
    }
    private function resolveJobCategoryTerm($identity): ?WP_Term
    {
        $taxonomy = $this->getJobCategoryTaxonomy();
        if (is_int($identity)) {
            $term = get_term($identity, $taxonomy);
            if ($term instanceof WP_Term) {
                return $term;
            }
        }
        if (is_string($identity)) {
            $candidate = trim(strval($identity));
            if ('' !== $candidate) {
                $term = get_term_by('slug', $candidate, $taxonomy);
                if ($term instanceof WP_Term) {
                    return $term;
                }
                $term = get_term_by('name', $candidate, $taxonomy);
                if ($term instanceof WP_Term) {
                    return $term;
                }
            }
        }
        return null;
    }
    private function extractJobCategoryTermArgs(WP_REST_Request $request): array
    {
        $args = [];
        $description = $request->get_param('description');
        if (is_string($description)) {
            $args['description'] = $description;
        }
        $slug = $request->get_param('slug');
        if (is_string($slug) && '' !== trim($slug)) {
            $args['slug'] = sanitize_title($slug);
        }
        $parent = $request->get_param('parent');
        if (null !== $parent) {
            $args['parent'] = max(0, (int) $parent);
        }
        return $args;
    }
    private function validateJobCategoryIdentity($value)
    {
        if (null === $value) {
            return new WP_Error('wpk_job_category_missing_identifier', 'Missing identifier for JobCategory.', ['status' => 400]);
        }
        if (is_string($value) && '' === trim($value)) {
            return new WP_Error('wpk_job_category_missing_identifier', 'Missing identifier for JobCategory.', ['status' => 400]);
        }
        if (!is_numeric($value)) {
            return new WP_Error('wpk_job_category_invalid_identifier', 'Invalid identifier for JobCategory.', ['status' => 400]);
        }
        $value = (int) $value;
        if ($value <= 0) {
            return new WP_Error('wpk_job_category_invalid_identifier', 'Invalid identifier for JobCategory.', ['status' => 400]);
        }
        return $value;
    }
}
// WPK:END AUTO
