<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources.job
 * Schema: job (manual)
 * Route: [DELETE] /acme/v1/jobs/:id
 * Route: [GET] /acme/v1/jobs
 * Route: [GET] /acme/v1/jobs/:id
 * Route: [PATCH] /acme/v1/jobs/:id
 * Route: [POST] /acme/v1/jobs
 */
namespace Acme\Jobs\Generated\Rest;

use Acme\Jobs\Generated\Capability\Capability;
use WP_Error;
use WP_Post;
use WP_Query;
use WP_REST_Request;
use function is_wp_error;
// WPK:BEGIN AUTO
final class JobController extends BaseController
{
    public function get_resource_name(): string
    {
        return 'job';
    }
    public function get_schema_key(): string
    {
        return 'job';
    }
    public function get_rest_args(): array
    {
        return ['created_at' => ['required' => true, 'schema' => ['format' => 'date-time', 'type' => 'string']], 'department' => ['description' => 'Filter jobs by department taxonomy term.', 'schema' => ['enum' => ['engineering', 'marketing', 'sales', 'operations'], 'type' => 'string']], 'id' => ['identity' => ['param' => 'id', 'type' => 'number'], 'required' => true, 'schema' => ['type' => 'integer']], 'location' => ['description' => 'Filter jobs by location model.', 'schema' => ['enum' => ['remote', 'onsite', 'hybrid'], 'type' => 'string']], 'salary_max' => ['schema' => ['type' => 'number']], 'salary_min' => ['schema' => ['type' => 'number']], 'search' => ['description' => 'Free text search across title and location.', 'schema' => ['type' => 'string']], 'status' => ['required' => true, 'schema' => ['enum' => ['draft', 'publish', 'closed'], 'type' => 'string']], 'title' => ['required' => true, 'schema' => ['type' => 'string']], 'updated_at' => ['schema' => ['format' => 'date-time', 'type' => 'string']]];
    }
    /**
     * Handle [DELETE] /acme/v1/jobs/:id.
     * @wp-kernel route-kind remove
     * @wp-kernel resource.wpPost.mutation delete
     */
    public function deleteAcmeV1JobsId(WP_REST_Request $request)
    {
        $id = (int) $request->get_param('id');
        
        $permission = Capability::enforce('job.remove', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $id = $request->get_param('id');
        if (null === $id) {
            return new WP_Error('wpk_job_missing_identifier', 'Missing identifier for Job.', ['status' => 400]);
        }
        $id = (int) $id;
        if ($id <= 0) {
            return new WP_Error('wpk_job_invalid_identifier', 'Invalid identifier for Job.', ['status' => 400]);
        }
        $post = $this->resolveJobPost($id);
        if (!$post instanceof WP_Post) {
            return new WP_Error('wpk_job_not_found', 'Job not found.', ['status' => 404]);
        }
        $previous = $this->prepareJobResponse($post, $request);
        $deleted = wp_delete_post($post->ID, true);
        if (false === $deleted) {
            return new WP_Error('wpk_job_delete_failed', 'Unable to delete Job.', ['status' => 500]);
        }
        return ['deleted' => true, 'id' => (int) $post->ID, 'previous' => $previous];
    }
    /**
     * Handle [GET] /acme/v1/jobs.
     * @wp-kernel route-kind list
     */
    public function getAcmeV1Jobs(WP_REST_Request $request)
    {
        $permission = Capability::enforce('job.list', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $post_type = $this->getJobPostType();
        $per_page = (int) $request->get_param('per_page');
        if ($per_page <= 0) {
            $per_page = 10;
        }
        if ($per_page > 100) {
            $per_page = 100;
        }
        
        $statuses = $this->getJobStatuses();
        
        $query_args = ['post_type' => $post_type, 'post_status' => $statuses, 'fields' => 'ids', 'paged' => max(1, (int) $request->get_param('page')), 'posts_per_page' => $per_page];
        
        $meta_query = [];
        $salary_minMeta = $request->get_param('salary_min');
        if ($salary_minMeta !== null) {
            $salary_minMeta = match (is_scalar($salary_minMeta)) {
                true => trim((string) $salary_minMeta),
                default => null,
            };
            if ($salary_minMeta !== null && $salary_minMeta !== '') {
                $meta_query[] = ['key' => 'salary_min', 'compare' => '=', 'value' => $salary_minMeta];
            }
        }
        $salary_maxMeta = $request->get_param('salary_max');
        if ($salary_maxMeta !== null) {
            $salary_maxMeta = match (is_scalar($salary_maxMeta)) {
                true => trim((string) $salary_maxMeta),
                default => null,
            };
            if ($salary_maxMeta !== null && $salary_maxMeta !== '') {
                $meta_query[] = ['key' => 'salary_max', 'compare' => '=', 'value' => $salary_maxMeta];
            }
        }
        $locationMeta = $request->get_param('location');
        if ($locationMeta !== null) {
            $locationMeta = match (is_scalar($locationMeta)) {
                true => trim((string) $locationMeta),
                default => null,
            };
            if ($locationMeta !== null && $locationMeta !== '') {
                $meta_query[] = ['key' => 'location', 'compare' => '=', 'value' => $locationMeta];
            }
        }
        $external_urlMeta = $request->get_param('external_url');
        if ($external_urlMeta !== null) {
            $external_urlMeta = match (is_scalar($external_urlMeta)) {
                true => trim((string) $external_urlMeta),
                default => null,
            };
            if ($external_urlMeta !== null && $external_urlMeta !== '') {
                $meta_query[] = ['key' => 'external_url', 'compare' => '=', 'value' => $external_urlMeta];
            }
        }
        if (count($meta_query) > 0) {
            $query_args['meta_query'] = $meta_query;
        }
        
        $tax_query = [];
        $acme_job_departmentTerms = $request->get_param('acme_job_department');
        if ($acme_job_departmentTerms !== null) {
            $acme_job_departmentTerms = array_filter(array_map(static fn($value) => (int) $value, (array) $acme_job_departmentTerms), static fn($value) => $value > 0);
            if (count($acme_job_departmentTerms) > 0) {
                $tax_query[] = ['taxonomy' => 'acme_job_department', 'field' => 'term_id', 'terms' => $acme_job_departmentTerms];
            }
        }
        $acme_job_locationTerms = $request->get_param('acme_job_location');
        if ($acme_job_locationTerms !== null) {
            $acme_job_locationTerms = array_filter(array_map(static fn($value) => (int) $value, (array) $acme_job_locationTerms), static fn($value) => $value > 0);
            if (count($acme_job_locationTerms) > 0) {
                $tax_query[] = ['taxonomy' => 'acme_job_location', 'field' => 'term_id', 'terms' => $acme_job_locationTerms];
            }
        }
        if (count($tax_query) > 0) {
            $query_args['tax_query'] = $tax_query;
        }
        
        $query = new WP_Query($query_args);
        
        $items = [];
        
        foreach ($query->posts as $post_id) {
            $post = get_post($post_id);
            if (!$post instanceof WP_Post) {
                continue;
            }
            $items[] = $this->prepareJobResponse($post, $request);
        }
        
        return ['items' => $items, 'total' => (int) $query->found_posts, 'pages' => (int) $query->max_num_pages];
    }
    /**
     * Handle [GET] /acme/v1/jobs/:id.
     * @wp-kernel route-kind get
     */
    public function getAcmeV1JobsId(WP_REST_Request $request)
    {
        $id = (int) $request->get_param('id');
        
        $permission = Capability::enforce('job.get', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        if (null === $id) {
            return new WP_Error('wpk_job_missing_identifier', 'Missing identifier for Job.', ['status' => 400]);
        }
        $id = (int) $id;
        if ($id <= 0) {
            return new WP_Error('wpk_job_invalid_identifier', 'Invalid identifier for Job.', ['status' => 400]);
        }
        
        $post = $this->resolveJobPost($id);
        if (!$post instanceof WP_Post) {
            return new WP_Error('wpk_job_not_found', 'Job not found.', ['status' => 404]);
        }
        
        return $this->prepareJobResponse($post, $request);
    }
    /**
     * Handle [PATCH] /acme/v1/jobs/:id.
     * @wp-kernel route-kind update
     * @wp-kernel resource.wpPost.mutation update
     */
    public function patchAcmeV1JobsId(WP_REST_Request $request)
    {
        $id = (int) $request->get_param('id');
        
        $permission = Capability::enforce('job.update', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $id = $request->get_param('id');
        if (null === $id) {
            return new WP_Error('wpk_job_missing_identifier', 'Missing identifier for Job.', ['status' => 400]);
        }
        $id = (int) $id;
        if ($id <= 0) {
            return new WP_Error('wpk_job_invalid_identifier', 'Invalid identifier for Job.', ['status' => 400]);
        }
        $post = $this->resolveJobPost($id);
        if (!$post instanceof WP_Post) {
            return new WP_Error('wpk_job_not_found', 'Job not found.', ['status' => 404]);
        }
        $post_data = ['ID' => $post->ID, 'post_type' => $this->getJobPostType()];
        // @wp-kernel resource.wpPost.mutation status-validation
        // @wp-kernel mutation:status normalise
        $status = $request->get_param('status');
        if (null !== $status) {
            $post_data['post_status'] = $this->normaliseJobStatus($status);
        }
        $result = wp_update_post($post_data, true);
        if (is_wp_error($result)) {
            return $result;
        }
        if (0 === $result) {
            return new WP_Error('wpk_job_update_failed', 'Unable to update Job.', ['status' => 500]);
        }
        // @wp-kernel resource.wpPost.mutation sync-meta
        // @wp-kernel mutation:meta update
        $this->syncJobMeta($post->ID, $request);
        // @wp-kernel resource.wpPost.mutation sync-taxonomies
        // @wp-kernel mutation:taxonomies update
        $taxonomy_result = $this->syncJobTaxonomies($post->ID, $request);
        if (is_wp_error($taxonomy_result)) {
            return $taxonomy_result;
        }
        // @wp-kernel resource.wpPost.mutation cache-priming
        // @wp-kernel mutation:cache prime
        // @wp-kernel cache:wp-post prime
        $updated = get_post($post->ID);
        if (!$updated instanceof WP_Post) {
            return new WP_Error('wpk_job_load_failed', 'Unable to load updated Job.', ['status' => 500]);
        }
        return $this->prepareJobResponse($updated, $request);
    }
    /**
     * Handle [POST] /acme/v1/jobs.
     * @wp-kernel route-kind create
     * @wp-kernel resource.wpPost.mutation create
     */
    public function postAcmeV1Jobs(WP_REST_Request $request)
    {
        $permission = Capability::enforce('job.create', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $post_type = $this->getJobPostType();
        $post_data = ['post_type' => $post_type];
        // @wp-kernel resource.wpPost.mutation status-validation
        // @wp-kernel mutation:status normalise
        $status = $request->get_param('status');
        $post_data['post_status'] = $this->normaliseJobStatus($status);
        $post_id = wp_insert_post($post_data, true);
        if (is_wp_error($post_id)) {
            return $post_id;
        }
        if (0 === $post_id) {
            return new WP_Error('wpk_job_create_failed', 'Unable to create Job.', ['status' => 500]);
        }
        // @wp-kernel resource.wpPost.mutation sync-meta
        // @wp-kernel mutation:meta update
        $this->syncJobMeta($post_id, $request);
        // @wp-kernel resource.wpPost.mutation sync-taxonomies
        // @wp-kernel mutation:taxonomies update
        $taxonomy_result = $this->syncJobTaxonomies($post_id, $request);
        if (is_wp_error($taxonomy_result)) {
            return $taxonomy_result;
        }
        // @wp-kernel resource.wpPost.mutation cache-priming
        // @wp-kernel mutation:cache prime
        // @wp-kernel cache:wp-post prime
        $post = get_post($post_id);
        if (!$post instanceof WP_Post) {
            return new WP_Error('wpk_job_load_failed', 'Unable to load created Job.', ['status' => 500]);
        }
        return $this->prepareJobResponse($post, $request);
    }
    private function syncJobMeta(int $post_id, WP_REST_Request $request): void
    {
        $salary_minMeta = $request->get_param('salary_min');
        if (null !== $salary_minMeta) {
            $salary_minMeta = is_numeric($salary_minMeta) ? (double) $salary_minMeta : 0.0;
            update_post_meta($post_id, 'salary_min', $salary_minMeta);
        }
        $salary_maxMeta = $request->get_param('salary_max');
        if (null !== $salary_maxMeta) {
            $salary_maxMeta = is_numeric($salary_maxMeta) ? (double) $salary_maxMeta : 0.0;
            update_post_meta($post_id, 'salary_max', $salary_maxMeta);
        }
        $locationMeta = $request->get_param('location');
        if (null !== $locationMeta) {
            $locationMeta = is_string($locationMeta) ? $locationMeta : (string) $locationMeta;
            update_post_meta($post_id, 'location', $locationMeta);
        }
        $external_urlMeta = $request->get_param('external_url');
        if (null !== $external_urlMeta) {
            $external_urlMeta = is_string($external_urlMeta) ? $external_urlMeta : (string) $external_urlMeta;
            update_post_meta($post_id, 'external_url', $external_urlMeta);
        }
    }
    private function syncJobTaxonomies(int $post_id, WP_REST_Request $request)
    {
        $result = true;
        $acme_job_departmentTerms = $request->get_param('acme_job_department');
        if (null !== $acme_job_departmentTerms) {
            if (!is_array($acme_job_departmentTerms)) {
                $acme_job_departmentTerms = [$acme_job_departmentTerms];
            }
            $acme_job_departmentTerms = array_filter(array_map('intval', (array) $acme_job_departmentTerms));
            $result = wp_set_object_terms($post_id, $acme_job_departmentTerms, 'acme_job_department', false);
            if (is_wp_error($result)) {
                return $result;
            }
        }
        $acme_job_locationTerms = $request->get_param('acme_job_location');
        if (null !== $acme_job_locationTerms) {
            if (!is_array($acme_job_locationTerms)) {
                $acme_job_locationTerms = [$acme_job_locationTerms];
            }
            $acme_job_locationTerms = array_filter(array_map('intval', (array) $acme_job_locationTerms));
            $result = wp_set_object_terms($post_id, $acme_job_locationTerms, 'acme_job_location', false);
            if (is_wp_error($result)) {
                return $result;
            }
        }
        return $result;
    }
    private function prepareJobResponse(WP_Post $post, WP_REST_Request $request): array
    {
        $data = ['id' => (int) $post->ID, 'status' => (string) $post->post_status];
        $data['title'] = (string) $post->post_title;
        $data['content'] = (string) $post->post_content;
        $data['excerpt'] = (string) $post->post_excerpt;
        $data['meta'] = get_post_meta($post->ID);
        $salary_minMeta = get_post_meta($post->ID, 'salary_min', true);
        $salary_minMeta = is_numeric($salary_minMeta) ? (double) $salary_minMeta : 0.0;
        $data['salary_min'] = $salary_minMeta;
        $salary_maxMeta = get_post_meta($post->ID, 'salary_max', true);
        $salary_maxMeta = is_numeric($salary_maxMeta) ? (double) $salary_maxMeta : 0.0;
        $data['salary_max'] = $salary_maxMeta;
        $locationMeta = get_post_meta($post->ID, 'location', true);
        $locationMeta = is_string($locationMeta) ? $locationMeta : (string) $locationMeta;
        $data['location'] = $locationMeta;
        $external_urlMeta = get_post_meta($post->ID, 'external_url', true);
        $external_urlMeta = is_string($external_urlMeta) ? $external_urlMeta : (string) $external_urlMeta;
        $data['external_url'] = $external_urlMeta;
        $acme_job_departmentTerms = wp_get_object_terms($post->ID, 'acme_job_department', ['fields' => 'ids']);
        if (is_wp_error($acme_job_departmentTerms)) {
            $acme_job_departmentTerms = [];
        }
        $acme_job_departmentTerms = array_map('intval', (array) $acme_job_departmentTerms);
        $data['acme_job_department'] = $acme_job_departmentTerms;
        $acme_job_locationTerms = wp_get_object_terms($post->ID, 'acme_job_location', ['fields' => 'ids']);
        if (is_wp_error($acme_job_locationTerms)) {
            $acme_job_locationTerms = [];
        }
        $acme_job_locationTerms = array_map('intval', (array) $acme_job_locationTerms);
        $data['acme_job_location'] = $acme_job_locationTerms;
        return $data;
    }
}
// WPK:END AUTO
