<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources.settings
 * Schema: settings (manual)
 * Route: [GET] /acme/v1/settings
 * Route: [PATCH] /acme/v1/settings
 */
namespace Acme\Jobs\Generated\Rest;

use Acme\Jobs\Generated\Capability\Capability;
use WP_Error;
use WP_REST_Request;
use function is_wp_error;
// WPK:BEGIN AUTO
final class SettingsController extends BaseController
{
    public function get_resource_name(): string
    {
        return 'settings';
    }
    public function get_schema_key(): string
    {
        return 'settings';
    }
    public function get_rest_args(): array
    {
        return ['auto_archive' => ['schema' => ['type' => 'boolean']], 'notify_email' => ['required' => true, 'schema' => ['format' => 'email', 'type' => 'string']], 'retention_days' => ['required' => true, 'schema' => ['maximum' => 3650, 'minimum' => 1, 'type' => 'integer']]];
    }
    /**
     * Handle [GET] /acme/v1/settings.
     * @wp-kernel route-kind custom
     */
    public function getAcmeV1Settings(WP_REST_Request $request)
    {
        $permission = Capability::enforce('settings.get', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $option_name = $this->getSettingsOptionName();
        $value = get_option($option_name);
        
        return ['option' => $option_name, 'value' => $value];
    }
    /**
     * Handle [PATCH] /acme/v1/settings.
     * @wp-kernel route-kind custom
     */
    public function patchAcmeV1Settings(WP_REST_Request $request)
    {
        $permission = Capability::enforce('settings.update', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $option_name = $this->getSettingsOptionName();
        $previous = get_option($option_name);
        $value = $request->get_param('value');
        $autoload = $this->normaliseSettingsAutoload($request->get_param('autoload'));
        
        $updated = null !== $autoload ? update_option($option_name, $value, $autoload) : update_option($option_name, $value);
        
        $value_after = get_option($option_name);
        
        return ['option' => $option_name, 'updated' => (bool) $updated, 'value' => $value_after, 'previous' => $previous];
    }
    private function getSettingsOptionName(): string
    {
        return 'acme_jobs_settings';
    }
    private function normaliseSettingsAutoload($value): ?string
    {
        if (null === $value) {
            return null;
        }
        if (is_bool($value)) {
            if ($value) {
                return 'yes';
            }
            return 'no';
        }
        if (is_numeric($value)) {
            if ((int) $value === 1) {
                return 'yes';
            }
            return 'no';
        }
        if (!is_string($value)) {
            return null;
        }
        $normalised = strtolower(trim((string) $value));
        if (in_array($normalised, ['1', 'true', 'yes'], true)) {
            return 'yes';
        }
        if (in_array($normalised, ['0', 'false', 'no'], true)) {
            return 'no';
        }
        return null;
    }
}
// WPK:END AUTO
