<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources.statusCache
 * Schema: auto:statusCache (auto)
 * Route: [GET] /acme/v1/status-cache/:slug
 * Route: [PUT] /acme/v1/status-cache/:slug
 */
namespace Acme\Jobs\Generated\Rest;

use Acme\Jobs\Generated\Capability\Capability;
use WP_Error;
use WP_REST_Request;
use function is_wp_error;
// WPK:BEGIN AUTO
final class StatusCacheController extends BaseController
{
    public function get_resource_name(): string
    {
        return 'statusCache';
    }
    public function get_schema_key(): string
    {
        return 'auto:statusCache';
    }
    public function get_rest_args(): array
    {
        return [];
    }
    /**
     * Handle [GET] /acme/v1/status-cache/:slug.
     * @wp-kernel route-kind get
     */
    public function getAcmeV1StatusCacheSlug(WP_REST_Request $request)
    {
        $slug = $request->get_param('slug');
        
        $permission = Capability::enforce('statusCache.get', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $key = $this->getStatusCacheTransientKey($slug);
        $value = get_transient($key);
        
        return ['key' => $key, 'value' => $value];
    }
    /**
     * Handle [PUT] /acme/v1/status-cache/:slug.
     * @wp-kernel route-kind update
     */
    public function putAcmeV1StatusCacheSlug(WP_REST_Request $request)
    {
        $slug = $request->get_param('slug');
        
        $permission = Capability::enforce('statusCache.update', $request);
        if (is_wp_error($permission)) {
            return $permission;
        }
        
        $key = $this->getStatusCacheTransientKey($slug);
        $previous = get_transient($key);
        $value = $request->get_param('value');
        $expiration = $this->normaliseStatusCacheExpiration($request->get_param('expiration'));
        
        $stored = set_transient($key, $value, $expiration);
        $current = get_transient($key);
        
        return ['key' => $key, 'stored' => (bool) $stored, 'value' => $current, 'previous' => $previous, 'expiration' => $expiration];
    }
    private function getStatusCacheTransientKey(...$segments): string
    {
        $parts = ['acme_jobs_status_cache'];
        foreach ($segments as $segment) {
            if (null !== $segment) {
                $normalised = trim((string) $segment);
                if (!('' === $normalised)) {
                    $parts[] = $normalised;
                }
            }
        }
        return implode('_', $parts);
    }
    private function normaliseStatusCacheExpiration($value): int
    {
        if (null === $value) {
            return 0;
        }
        if (is_int($value)) {
            return max(0, $value);
        }
        if (is_numeric($value)) {
            return max(0, (int) $value);
        }
        if (!is_string($value)) {
            return 0;
        }
        $sanitised = trim((string) $value);
        if ('' === $sanitised) {
            return 0;
        }
        if (is_numeric($sanitised)) {
            return max(0, (int) $sanitised);
        }
        return 0;
    }
}
// WPK:END AUTO
