import {
	AUTO_GUARD_BEGIN,
	AUTO_GUARD_END,
	DEFAULT_DOC_HEADER,
} from '../constants';
import {
	buildArg,
	buildArray,
	buildArrayItem,
	buildAssign,
	buildBinaryOperation,
	buildBooleanNot,
	buildComment,
	buildContinue,
	buildDeclare,
	buildDeclareItem,
	buildDocComment,
	buildForeach,
	buildFuncCall,
	buildExpressionStatement,
	buildIdentifier,
	buildIfStatement,
	buildMethodCall,
	buildName,
	buildFullyQualifiedName,
	buildNamespace,
	buildNew,
	buildReturn,
	buildScalarInt,
	buildScalarString,
	buildStmtNop,
	buildVariable,
	buildNode,
	mergeNodeAttributes,
	type PhpExprConstFetch,
	type PhpProgram,
	type PhpStmt,
	type PhpStmtFunction,
} from '@wpkernel/php-json-ast';

export interface PluginLoaderProgramConfig {
	readonly origin: string;
	readonly namespace: string;
	readonly sanitizedNamespace: string;
	readonly resourceClassNames: readonly string[];
}

export function buildPluginLoaderProgram(
	config: PluginLoaderProgramConfig
): PhpProgram {
	const pluginHeader = buildPluginHeaderStatement(config);
	const strictTypes = buildDeclare([
		buildDeclareItem('strict_types', buildScalarInt(1)),
	]);

	const namespaceStatements = buildNamespaceStatements(config);

	return [pluginHeader, strictTypes, namespaceStatements];
}

function buildNamespaceStatements(config: PluginLoaderProgramConfig): PhpStmt {
	const namespaceNode = buildName(splitNamespace(config.namespace));
	const statements: PhpStmt[] = [];

	statements.push(
		buildStmtNop({
			comments: [
				buildDocComment([
					...DEFAULT_DOC_HEADER,
					`Source: ${config.origin} → plugin/loader`,
				]),
			],
		})
	);
	statements.push(
		buildStmtNop({ comments: [buildComment(`// ${AUTO_GUARD_BEGIN}`)] })
	);
	statements.push(buildAccessGuardStatement());
	statements.push(buildGetControllersFunction(config));
	statements.push(buildRegisterRoutesFunction());
	statements.push(buildBootstrapFunction());
	statements.push(buildBootstrapInvocation());
	statements.push(
		buildStmtNop({ comments: [buildComment(`// ${AUTO_GUARD_END}`)] })
	);

	return buildNamespace(namespaceNode, statements);
}

function buildPluginHeaderStatement(
	config: PluginLoaderProgramConfig
): PhpStmt {
	const title = buildPluginTitle(config.sanitizedNamespace);
	const packageName = config.namespace.replace(/\\/g, '');
	const lines: string[] = [
		`Plugin Name: ${title}`,
		`Description: Bootstrap loader for the ${title} WP Kernel integration.`,
		'Version: 0.1.0',
		'Requires at least: 6.7',
		'Requires PHP: 8.1',
		`Text Domain: ${config.sanitizedNamespace}`,
		'Author: WP Kernel Contributors',
		'Author URI: https://github.com/thegeekist/wp-kernel',
		'License: GPL-2.0-or-later',
		'License URI: https://www.gnu.org/licenses/gpl-2.0.html',
		'Generated by WP Kernel CLI - edits between WPK:BEGIN AUTO and WPK:END AUTO are managed by the generator.',
		`Source: ${config.origin} → plugin/loader`,
		`@package ${packageName}`,
	];

	return buildStmtNop({
		comments: [buildDocComment(lines)],
	});
}

function buildAccessGuardStatement(): PhpStmt {
	const definedCall = buildFuncCall(buildName(['defined']), [
		buildArg(buildScalarString('ABSPATH')),
	]);
	const guardCondition = buildBooleanNot(definedCall);
	const exitCall = buildFuncCall(buildName(['exit']));

	return buildIfStatement(guardCondition, [
		buildExpressionStatement(exitCall),
	]);
}

function buildGetControllersFunction(
	config: PluginLoaderProgramConfig
): PhpStmtFunction {
	const returnArray = buildArray(
		config.resourceClassNames.map((className) =>
			buildArrayItem(
				buildNew(buildFullyQualifiedName(splitNamespace(className)))
			)
		)
	);

	const returnStatement = buildReturn(returnArray);

	const fn = buildNodeFunction('get_kernel_controllers', {
		returnType: buildIdentifier('array'),
		statements: [returnStatement],
	});

	return mergeNodeAttributes(fn, {
		comments: [
			buildDocComment([
				'Retrieve WP Kernel REST controllers generated for this plugin.',
				'@return array<int, object>',
			]),
		],
	});
}

function buildRegisterRoutesFunction(): PhpStmtFunction {
	const controllersAssignment = buildExpressionStatement(
		buildAssign(
			buildVariable('controllers'),
			buildFuncCall(buildName(['get_kernel_controllers']))
		)
	);

	const methodExistsCall = buildFuncCall(buildName(['method_exists']), [
		buildArg(buildVariable('controller')),
		buildArg(buildScalarString('register_routes')),
	]);

	const guard = buildIfStatement(buildBooleanNot(methodExistsCall), [
		buildContinue(),
	]);

	const registerCall = buildExpressionStatement(
		buildMethodCall(
			buildVariable('controller'),
			buildIdentifier('register_routes')
		)
	);

	const foreachLoop = buildForeach(buildVariable('controllers'), {
		valueVar: buildVariable('controller'),
		stmts: [guard, registerCall],
	});

	const fn = buildNodeFunction('register_kernel_routes', {
		returnType: buildIdentifier('void'),
		statements: [controllersAssignment, foreachLoop],
	});

	return mergeNodeAttributes(fn, {
		comments: [
			buildDocComment([
				'Register WP Kernel REST controllers with WordPress.',
			]),
		],
	});
}

function buildBootstrapFunction(): PhpStmtFunction {
	const namespaceConst = buildConstFetchExpression('__NAMESPACE__');
	const callback = buildBinaryOperation(
		'Concat',
		namespaceConst,
		buildScalarString('\\register_kernel_routes')
	);

	const addActionCall = buildExpressionStatement(
		buildFuncCall(buildName(['add_action']), [
			buildArg(buildScalarString('rest_api_init')),
			buildArg(callback),
		])
	);

	const fn = buildNodeFunction('bootstrap_kernel', {
		returnType: buildIdentifier('void'),
		statements: [addActionCall],
	});

	return mergeNodeAttributes(fn, {
		comments: [
			buildDocComment([
				'Attach kernel hooks required for REST registration.',
			]),
		],
	});
}

function buildBootstrapInvocation(): PhpStmt {
	return buildExpressionStatement(
		buildFuncCall(buildName(['bootstrap_kernel']))
	);
}

function buildNodeFunction(
	name: string,
	options: {
		readonly returnType: ReturnType<typeof buildIdentifier> | null;
		readonly statements: readonly PhpStmt[];
	}
): PhpStmtFunction {
	return buildNode<PhpStmtFunction>('Stmt_Function', {
		byRef: false,
		name: buildIdentifier(name),
		params: [],
		returnType: options.returnType,
		stmts: [...options.statements],
		attrGroups: [],
		namespacedName: null,
	});
}

function buildConstFetchExpression(name: string): PhpExprConstFetch {
	return buildNode('Expr_ConstFetch', {
		name: buildName([name]),
	});
}

function splitNamespace(value: string): string[] {
	return value.split('\\').filter(Boolean);
}

function buildPluginTitle(sanitized: string): string {
	if (!sanitized) {
		return 'WP Kernel Plugin';
	}

	return sanitized
		.split('-')
		.filter(Boolean)
		.map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
		.join(' ');
}
