<?php

/**
 * Plugin Name: Acme Jobs
 * Description: Bootstrap loader for the Acme Jobs WPKernel integration.
 * Version: 0.1.0
 * Requires at least: 6.7
 * Requires PHP: 8.1
 * Text Domain: acme-jobs
 * Author: WPKernel Contributors
 * License: GPL-2.0-or-later
 * Generated by WPKernel CLI - edits between WPK:BEGIN AUTO and WPK:END AUTO are managed by the generator.
 * Source: wpk.config.ts → plugin/loader
 * @package AcmeJobs
 */
declare(strict_types=1);
namespace Acme\Jobs;

/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → plugin/loader
 */
// WPK:BEGIN AUTO
if (!defined('ABSPATH')) {
    exit();
}
/**
 * Retrieve WPKernel REST controllers generated for this plugin.
 * @return array<int, object>
 */
function get_wpkernel_controllers(): array
{
    $classmapPath = plugin_dir_path(__FILE__) . '.wpk/generate/php/index.php';
    if (file_exists($classmapPath)) {
        $classmap = require($classmapPath);
        if (is_array($classmap)) {
            foreach ($classmap as $class => $path) {
                if (!class_exists($class) && file_exists($path)) {
                    require_once($path);
                }
            }
        }
    }
    require_once __DIR__ . '/inc/Rest/ApplicationController.php';
    require_once __DIR__ . '/inc/Rest/JobController.php';
    require_once __DIR__ . '/inc/Rest/JobCategoryController.php';
    require_once __DIR__ . '/inc/Rest/SettingsController.php';
    require_once __DIR__ . '/inc/Rest/StatusCacheController.php';
    return [new \Acme\Jobs\Rest\ApplicationController(), new \Acme\Jobs\Rest\JobController(), new \Acme\Jobs\Rest\JobCategoryController(), new \Acme\Jobs\Rest\SettingsController(), new \Acme\Jobs\Rest\StatusCacheController()];
}
/** Register WPKernel REST controllers with WordPress. */
function register_wpkernel_routes(): void
{
    $controllers = get_wpkernel_controllers();
    foreach ($controllers as $controller) {
        if (!method_exists($controller, 'register_routes')) {
            continue;
        }
        $controller->register_routes();
    }
}
/** Register content model (post types, taxonomies, statuses) for generated resources. */
function register_wpkernel_content_model(): void
{
    register_post_status('rejected', ['label' => 'Rejected', 'public' => false, 'show_in_admin_all_list' => true, 'show_in_admin_status_list' => true, 'label_count' => _n_noop('Rejected <span class="count">(%s)</span>', 'Rejected <span class="count">(%s)</span>')]);
    register_post_status('hired', ['label' => 'Hired', 'public' => false, 'show_in_admin_all_list' => true, 'show_in_admin_status_list' => true, 'label_count' => _n_noop('Hired <span class="count">(%s)</span>', 'Hired <span class="count">(%s)</span>')]);
    register_post_status('closed', ['label' => 'Closed', 'public' => false, 'show_in_admin_all_list' => true, 'show_in_admin_status_list' => true, 'label_count' => _n_noop('Closed <span class="count">(%s)</span>', 'Closed <span class="count">(%s)</span>')]);
    register_post_type('acme_application', ['labels' => ['name' => 'Applications', 'singular_name' => 'Application', 'add_new_item' => 'Add New Application', 'edit_item' => 'Edit Application', 'new_item' => 'New Application', 'view_item' => 'View Application', 'search_items' => 'Search Applications', 'not_found' => 'No applications found', 'not_found_in_trash' => 'No applications found in Trash', 'all_items' => 'All Applications', 'menu_name' => 'Applications'], 'supports' => ['custom-fields'], 'show_ui' => false, 'show_in_menu' => false, 'show_in_rest' => true, 'rewrite' => false, 'capability_type' => 'post', 'map_meta_cap' => true, 'public' => false]);
    register_post_type('acme_job', ['labels' => ['name' => 'Jobs', 'singular_name' => 'Job', 'add_new_item' => 'Add New Job', 'edit_item' => 'Edit Job', 'new_item' => 'New Job', 'view_item' => 'View Job', 'search_items' => 'Search Jobs', 'not_found' => 'No jobs found', 'not_found_in_trash' => 'No jobs found in Trash', 'all_items' => 'All Jobs', 'menu_name' => 'Jobs'], 'supports' => ['title', 'editor', 'excerpt', 'custom-fields'], 'taxonomies' => ['acme_job_department', 'acme_job_location'], 'show_ui' => false, 'show_in_menu' => false, 'show_in_rest' => true, 'rewrite' => false, 'capability_type' => 'post', 'map_meta_cap' => true, 'public' => false]);
    register_taxonomy('acme_job_department', ['acme_job'], ['labels' => ['name' => 'Acme Job Departments', 'singular_name' => 'Acme Job Department', 'search_items' => 'Search Acme Job Departments', 'all_items' => 'All Acme Job Departments', 'parent_item' => 'Parent Acme Job Department', 'parent_item_colon' => 'Parent Acme Job Department:', 'edit_item' => 'Edit Acme Job Department', 'update_item' => 'Update Acme Job Department', 'add_new_item' => 'Add New Acme Job Department', 'new_item_name' => 'New Acme Job Department Name', 'menu_name' => 'Acme Job Departments'], 'hierarchical' => false, 'show_ui' => true, 'show_admin_column' => true, 'show_in_rest' => true]);
    register_taxonomy('acme_job_location', ['acme_job'], ['labels' => ['name' => 'Acme Job Locations', 'singular_name' => 'Acme Job Location', 'search_items' => 'Search Acme Job Locations', 'all_items' => 'All Acme Job Locations', 'parent_item' => 'Parent Acme Job Location', 'parent_item_colon' => 'Parent Acme Job Location:', 'edit_item' => 'Edit Acme Job Location', 'update_item' => 'Update Acme Job Location', 'add_new_item' => 'Add New Acme Job Location', 'new_item_name' => 'New Acme Job Location Name', 'menu_name' => 'Acme Job Locations'], 'hierarchical' => true, 'show_ui' => true, 'show_admin_column' => true, 'show_in_rest' => true]);
    register_taxonomy('acme_job_category', [], ['labels' => ['name' => 'Acme Job Categorys', 'singular_name' => 'Acme Job Category', 'search_items' => 'Search Acme Job Categorys', 'all_items' => 'All Acme Job Categorys', 'parent_item' => 'Parent Acme Job Category', 'parent_item_colon' => 'Parent Acme Job Category:', 'edit_item' => 'Edit Acme Job Category', 'update_item' => 'Update Acme Job Category', 'add_new_item' => 'Add New Acme Job Category', 'new_item_name' => 'New Acme Job Category Name', 'menu_name' => 'Acme Job Categorys'], 'hierarchical' => true, 'show_ui' => true, 'show_admin_column' => true, 'show_in_rest' => true]);
}
/** Register and enqueue generated UI assets for DataViews screens. */
function enqueue_wpkernel_ui_assets(): void
{
    $page = isset($_GET['page']) ? sanitize_key(strval($_GET['page'])) : '';
    $plugin_pages = ['acme-applications', 'acme-jobs'];
    if (!in_array($page, $plugin_pages, true)) {
        return;
    }
    $asset_path = plugin_dir_path(__FILE__) . 'build/index.asset.json';
    if (!file_exists($asset_path)) {
        return;
    }
    $asset_contents = file_get_contents($asset_path);
    if ($asset_contents === false) {
        return;
    }
    $asset = json_decode($asset_contents, true);
    $dependencies = [];
    if (is_array($asset) && (isset($asset['dependencies']) && is_array($asset['dependencies']))) {
        $dependencies = $asset['dependencies'];
    }
    $core_bundles = ['wp-element' => 'element.min.js', 'wp-dataviews' => 'dataviews.min.js', 'wp-interactivity' => 'interactivity.min.js', 'wp-private-apis' => 'private-apis.min.js'];
    foreach ($core_bundles as $handle => $filename) {
        if (!in_array($handle, $dependencies, true)) {
            continue;
        }
        if (wp_script_is($handle, 'registered') || wp_script_is($handle, 'enqueued')) {
            continue;
        }
        wp_register_script($handle, includes_url('js/dist/' . $filename), [], get_bloginfo('version'), true);
    }
    $version = false;
    if (is_array($asset) && array_key_exists('version', $asset)) {
        $version = $asset['version'];
    }
    $script_url = plugins_url('build/index.js', __FILE__);
    wp_register_script('wp-acme-jobs-ui', $script_url, $dependencies, $version);
    $localization = ['namespace' => 'acme-jobs', 'resources' => [['resource' => 'application', 'preferencesKey' => 'acme-jobs/dataviews/application', 'menu' => ['slug' => 'acme-applications', 'title' => 'Applications', 'capability' => 'manage_options', 'parent' => 'acme-jobs']], ['resource' => 'job', 'preferencesKey' => 'acme-jobs/dataviews/job', 'menu' => ['slug' => 'acme-jobs', 'title' => 'Jobs', 'capability' => 'manage_options', 'position' => 58]]]];
    wp_localize_script('wp-acme-jobs-ui', 'wpKernelUISettings', $localization);
    $style_path = plugin_dir_path(__FILE__) . 'build/index.css';
    if (file_exists($style_path)) {
        wp_enqueue_style('wp-acme-jobs-ui', plugins_url('build/index.css', __FILE__), ['wp-components'], $version);
    }
    wp_enqueue_script('wp-acme-jobs-ui');
}
/** Register admin menu entries for WPKernel DataViews screens. */
function register_wpkernel_admin_menu(): void
{
    $parent_menus = [['slug' => 'acme-jobs', 'title' => 'Jobs', 'capability' => 'manage_options', 'position' => 58]];
    $child_menus = [['slug' => 'acme-applications', 'title' => 'Applications', 'capability' => 'manage_options', 'parent' => 'acme-jobs']];
    foreach ($parent_menus as $menu) {
        $slug = $menu['slug'];
        $title = $menu['title'];
        $capability = isset($menu['capability']) ? $menu['capability'] : 'manage_options';
        $callback = __NAMESPACE__ . '\render_wpkernel_admin_screen';
        if (isset($menu['parent']) && $menu['parent']) {
            if (isset($menu['position'])) {
                add_submenu_page($menu['parent'], $title, $title, $capability, $slug, $callback, $menu['position']);
            } else {
                add_submenu_page($menu['parent'], $title, $title, $capability, $slug, $callback);
            }
            continue;
        }
        if (isset($menu['position'])) {
            add_menu_page($title, $title, $capability, $slug, $callback, '', $menu['position']);
        } else {
            add_menu_page($title, $title, $capability, $slug, $callback, '');
        }
    }
    foreach ($child_menus as $menu) {
        $slug = $menu['slug'];
        $title = $menu['title'];
        $capability = isset($menu['capability']) ? $menu['capability'] : 'manage_options';
        $callback = __NAMESPACE__ . '\render_wpkernel_admin_screen';
        if (isset($menu['parent']) && $menu['parent']) {
            if (isset($menu['position'])) {
                add_submenu_page($menu['parent'], $title, $title, $capability, $slug, $callback, $menu['position']);
            } else {
                add_submenu_page($menu['parent'], $title, $title, $capability, $slug, $callback);
            }
            continue;
        }
        if (isset($menu['position'])) {
            add_menu_page($title, $title, $capability, $slug, $callback, '', $menu['position']);
        } else {
            add_menu_page($title, $title, $capability, $slug, $callback, '');
        }
    }
}
/** Render container for WPKernel-admin DataViews screens. */
function render_wpkernel_admin_screen(): void
{
    $page = '';
    if (isset($_GET['page'])) {
        $page = sanitize_key(strval($_GET['page']));
    }
    printf('<div class="wrap"><div id="wpkernel-admin-screen" data-wpkernel-page="%s"></div></div>', esc_attr($page));
}
/** Attach wpk hooks required for REST registration. */
function bootstrap_wpk(): void
{
    add_action('rest_api_init', __NAMESPACE__ . '\register_wpkernel_routes');
    add_action('init', __NAMESPACE__ . '\register_wpkernel_content_model', 5);
    add_action('admin_enqueue_scripts', __NAMESPACE__ . '\enqueue_wpkernel_ui_assets');
    add_action('admin_menu', __NAMESPACE__ . '\register_wpkernel_admin_menu');
}
bootstrap_wpk();
// WPK:END AUTO
// Custom plugin logic may be added below. This area is left untouched by the generator.
