<?php

/**
 * Plugin Name: Acme Jobs
 * Description: Bootstrap loader for the Acme Jobs WPKernel integration.
 * Version: 0.1.0
 * Requires at least: 6.7
 * Requires PHP: 8.1
 * Text Domain: acme-jobs
 * Author: WPKernel Contributors
 * Author URI: https://github.com/wpkernel/wpkernel
 * License: GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Generated by WPKernel CLI - edits between WPK:BEGIN AUTO and WPK:END AUTO are managed by the generator.
 * Source: wpk.config.ts → plugin/loader
 * @package AcmeJobs
 */
declare(strict_types=1);
namespace Acme\Jobs;

/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → plugin/loader
 */
// WPK:BEGIN AUTO
if (!defined('ABSPATH')) {
    exit();
}
/**
 * Retrieve WPKernel REST controllers generated for this plugin.
 * @return array<int, object>
 */
function get_wpkernel_controllers(): array
{
    return [new \Acme\Jobs\Generated\Rest\ApplicationController(), new \Acme\Jobs\Generated\Rest\JobController(), new \Acme\Jobs\Generated\Rest\JobCategoryController(), new \Acme\Jobs\Generated\Rest\SettingsController(), new \Acme\Jobs\Generated\Rest\StatusCacheController()];
}
/** Register WPKernel REST controllers with WordPress. */
function register_wpkernel_routes(): void
{
    $controllers = get_wpkernel_controllers();
    foreach ($controllers as $controller) {
        if (!method_exists($controller, 'register_routes')) {
            continue;
        }
        $controller->register_routes();
    }
}
/** Register and enqueue generated UI assets for DataViews screens. */
function enqueue_wpkernel_ui_assets(): void
{
    $asset_path = plugin_dir_path(__FILE__) . 'build/index.asset.json';
    if (!file_exists($asset_path)) {
        return;
    }
    $asset_contents = file_get_contents($asset_path);
    if ($asset_contents === false) {
        return;
    }
    $asset = json_decode($asset_contents, true);
    $dependencies = [];
    if (is_array($asset) && (isset($asset['dependencies']) && is_array($asset['dependencies']))) {
        $dependencies = $asset['dependencies'];
    }
    $version = false;
    if (is_array($asset) && array_key_exists('version', $asset)) {
        $version = $asset['version'];
    }
    $script_url = plugins_url('build/index.js', __FILE__);
    wp_register_script('wp-acme-jobs-ui', $script_url, $dependencies, $version);
    $localization = ['namespace' => 'acme-jobs', 'resources' => [['resource' => 'application', 'preferencesKey' => 'acme-jobs/dataviews/application'], ['resource' => 'job', 'preferencesKey' => 'acme-jobs/dataviews/job', 'menu' => ['slug' => 'acme-jobs', 'title' => 'Jobs', 'capability' => 'manage_options', 'parent' => 'options-general.php', 'position' => 58]]]];
    wp_localize_script('wp-acme-jobs-ui', 'wpKernelUISettings', $localization);
    wp_enqueue_script('wp-acme-jobs-ui');
}
/** Attach wpk hooks required for REST registration. */
function bootstrap_kernel(): void
{
    add_action('rest_api_init', __NAMESPACE__ . '\register_wpkernel_routes');
    add_action('admin_enqueue_scripts', __NAMESPACE__ . '\enqueue_wpkernel_ui_assets');
}
bootstrap_kernel();
// WPK:END AUTO
