<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → blocks.ssr.register
 */
namespace Acme\Jobs\Blocks;

use function register_block_type_from_metadata;
// WPK:BEGIN AUTO
final class Register
{
    public static function register(): void
    {
        $manifest_path = dirname(constant('__DIR__'), 2) . '/build/blocks-manifest.php';
        if (!file_exists($manifest_path)) {
            return;
        }
        $entries = require($manifest_path);
        if (!is_array($entries)) {
            return;
        }
        $plugin_root = dirname(constant('__DIR__'), 2);
        foreach ($entries as $block => $config) {
            if (!is_array($config)) {
                continue;
            }
            $metadata_path = self::resolve_config_path($plugin_root, $config, 'manifest');
            if (!$metadata_path) {
                $metadata_path = self::resolve_directory_fallback($plugin_root, $config);
            }
            if (!$metadata_path) {
                continue;
            }
            $render_path = self::resolve_render_path($plugin_root, $config);
            if ($render_path) {
                register_block_type_from_metadata($metadata_path, self::build_render_arguments($render_path));
                continue;
            }
            register_block_type_from_metadata($metadata_path);
        }
    }
    private static function resolve_config_path(string $root, array $config, string $key): ?string
    {
        if (empty($config[$key]) || !is_string($config[$key])) {
            return null;
        }
        $path = self::normalise_relative($root, $config[$key]);
        if (!file_exists($path)) {
            return null;
        }
        return $path;
    }
    private static function resolve_render_path(string $root, array $config): ?string
    {
        $path = self::resolve_config_path($root, $config, 'render');
        if ($path) {
            return $path;
        }
        $directory = self::resolve_directory_fallback($root, $config);
        if (!$directory) {
            return null;
        }
        $candidate = $directory . constant('DIRECTORY_SEPARATOR') . 'render.php';
        if (!file_exists($candidate)) {
            return null;
        }
        return $candidate;
    }
    private static function build_render_arguments(string $render_path): array
    {
        return ['render_callback' => static function (array $attributes = [], string $content = '', ?\WP_Block $block = null) use ($render_path): string {
            return self::render_template($render_path, $attributes, $content, $block);
        }];
    }
    private static function render_template(string $render_path, array $attributes, string $content, ?\WP_Block $block = null): string
    {
        if (!file_exists($render_path)) {
            return $content;
        }
        ob_start();
        require($render_path);
        return (string) ob_get_clean();
    }
    private static function resolve_directory_fallback(string $root, array $config): ?string
    {
        return self::resolve_config_path($root, $config, 'directory');
    }
    private static function normalise_relative(string $root, string $relative): string
    {
        $trimmed = ltrim($relative, '/');
        $normalised = str_replace('/', constant('DIRECTORY_SEPARATOR'), $trimmed);
        return rtrim($root, '/\\') . constant('DIRECTORY_SEPARATOR') . $normalised;
    }
}
// WPK:END AUTO
