export const DEFAULT_DOC_HEADER = [
	'AUTO-GENERATED by WP Kernel CLI.',
	'Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.',
] as const;

export const AUTO_GUARD_BEGIN = 'WPK:BEGIN AUTO';
export const AUTO_GUARD_END = 'WPK:END AUTO';
