import type { PhpAstBuilderAdapter } from '@wpkernel/php-json-ast';

import {
	appendGeneratedFileDocblock,
	buildGeneratedFileDocComment,
} from '../docblocks';
import { DEFAULT_DOC_HEADER } from '../constants';

describe('docblock helpers', () => {
	it('prefixes the generated docblock header before extra lines', () => {
		const lines: string[] = [];
		const builder = {
			appendDocblock: (line: string) => {
				lines.push(line);
			},
		} as unknown as PhpAstBuilderAdapter;

		appendGeneratedFileDocblock(builder, ['Example file']);

		expect(lines).toEqual([...DEFAULT_DOC_HEADER, 'Example file']);
	});

	it('builds a doc comment containing the header and provided lines', () => {
		const docComment = buildGeneratedFileDocComment(['Example file']);

		expect(docComment.text).toContain('AUTO-GENERATED by WP Kernel CLI.');
		expect(docComment.text).toContain('Example file');
	});
});
