/**
 * AUTO-GENERATED by WPKernel CLI.
 * Changes within this file will be overwritten. Regenerate via the CLI.
 * Source: wpk.config.ts → schemas.auto:job
 * Hash: b3340a2fcdbdfc1bb4a74180c621f3c9dad5d179e9512408468ccd9b0d54c4fe
 */

export interface JobResource {
	apply_deadline?: string;
	department?: string;
	job_type?: string;
	location?: string;
	remote_policy?: string;
	salary_max?: number;
	salary_min?: number;
	seniority?: string;
}
