<?php

declare(strict_types=1);
namespace Acme\Jobs\Rest;

/**
 * WPKernel extension shim.
 * Edits to this file will be preserved during apply operations.
 */
if (!class_exists(Acme\Jobs\Generated\Rest\StatusCacheController::class)) {
    require_once(__DIR__ . '/../../.generated/php/Rest/StatusCacheController.php');
}
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Source: wpk.config.ts → resources.statusCache
 * Schema: auto:statusCache (auto)
 */
class StatusCacheController extends Acme\Jobs\Generated\Rest\StatusCacheController
{
}
