/**
 * The beginning of an auto-generated code block.
 *
 * @category WordPress AST
 */
export const AUTO_GUARD_BEGIN = 'WPK:BEGIN AUTO';

/**
 * The end of an auto-generated code block.
 *
 * @category WordPress AST
 */
export const AUTO_GUARD_END = 'WPK:END AUTO';

/**
 * The default header for auto-generated files.
 *
 * @category WordPress AST
 */
export const DEFAULT_DOC_HEADER = [
	'AUTO-GENERATED by WPKernel CLI.',
	'Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.',
] as const;
