export {
	appendStatementsWithSpacing,
	buildArrayDimFetch,
	buildArrayInitialiserStatement,
	buildArrayLiteral,
	buildBinaryOperation,
	buildBooleanNot,
	buildForeachStatement,
	buildFunctionCall,
	buildFunctionCallAssignmentStatement,
	buildIfStatementNode,
	buildInstanceof,
	buildMethodCallAssignmentStatement,
	buildMethodCallExpression,
	buildPropertyFetch,
	buildReturnVoid,
	buildScalarCast,
	buildVariableAssignment,
	normaliseVariableReference,
} from '@wpkernel/wp-json-ast';
export type {
	ArrayInitialiserStatementOptions,
	ArrayLiteralEntry,
	ForeachStatementOptions,
	FunctionCallAssignmentOptions,
	IfStatementOptions,
	MethodCallAssignmentOptions,
	MethodCallExpressionOptions,
	MethodCallSubject,
	NormalisedVariableReference,
	ScalarCastKind,
} from '@wpkernel/wp-json-ast';
