<?php
/**
 * Plugin Name: __WPK_PLUGIN_TITLE__
 * Description: Bootstrap loader for the __WPK_PLUGIN_TITLE__ WP Kernel integration.
 * Version: 0.1.0
 * Requires at least: 6.7
 * Requires PHP: 8.1
 * Text Domain: __WPK_PLUGIN_TEXT_DOMAIN__
 * Author: WP Kernel Contributors
 * Author URI: https://github.com/thegeekist/wp-kernel
 * License: GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Generated by WP Kernel CLI - edits between WPK:BEGIN AUTO and WPK:END AUTO are managed by the generator.
 * Source: wpk.config.ts → plugin/loader
 * @package __WPK_PLUGIN_PACKAGE__
 */

declare(strict_types=1);

namespace __WPK_PHP_NAMESPACE__;

/**
 * This file is the main entry point for your plugin's PHP code.
 * It is responsible for bootstrapping the WP Kernel runtime and
 * registering your plugin's REST API routes.
 *
 * Edits between `WPK:BEGIN AUTO` and `WPK:END AUTO` are managed by the WP Kernel CLI.
 * You can add your own code outside of these blocks.
 *
 * @see https://github.com/theGeekist/wp-kernel/blob/main/docs/guide/actions.md
 * @see https://github.com/theGeekist/wp-kernel/blob/main/docs/guide/resources.md
 */
// WPK:BEGIN AUTO
if (!\defined('ABSPATH')) {
        exit;
}

/**
 * Retrieve WP Kernel REST controllers generated for this plugin.
 *
 * This function is auto-generated by the WP Kernel CLI.
 * It returns an array of all the REST controllers that are defined
 * in your `wpk.config.ts` file.
 *
 * @return array<int, object>
 */
function get_wpkernel_controllers(): array
{
        return [];
}

/**
 * Register WP Kernel REST controllers with WordPress.
 *
 * This function is auto-generated by the WP Kernel CLI.
 * It iterates over all the generated REST controllers and registers
 * their routes with WordPress.
 */
function register_wpkernel_routes(): void
{
        $controllers = get_wpkernel_controllers();

        foreach ($controllers as $controller) {
                if (!\method_exists($controller, 'register_routes')) {
                        continue;
                }

                $controller->register_routes();
        }
}

/**
 * Attach wpk hooks required for REST registration.
 *
 * This function is auto-generated by the WP Kernel CLI.
 * It hooks into the `rest_api_init` action to register your
 * plugin's REST API routes.
 */
function bootstrap_kernel(): void
{
        \add_action('rest_api_init', __NAMESPACE__ . '\\register_wpkernel_routes');
}

bootstrap_kernel();
// WPK:END AUTO
