<?php
/**
 * Plugin Name: __WPK_PLUGIN_TITLE__
 * Description: Bootstrap loader for the __WPK_PLUGIN_TITLE__ WP Kernel integration.
 * Version: 0.1.0
 * Requires at least: 6.7
 * Requires PHP: 8.1
 * Text Domain: __WPK_PLUGIN_TEXT_DOMAIN__
 * Author: WP Kernel Contributors
 * Author URI: https://github.com/thegeekist/wp-kernel
 * License: GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Generated by WP Kernel CLI — edits between WPK:BEGIN AUTO and WPK:END AUTO are managed by the generator.
 * Source: wpk.config.ts → plugin/loader
 * @package __WPK_PLUGIN_PACKAGE__
 */

declare(strict_types=1);

namespace __WPK_PHP_NAMESPACE__;

/**
 * AUTO-GENERATED by WP Kernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → plugin/loader
 */
// WPK:BEGIN AUTO
if (!\defined('ABSPATH')) {
        exit;
}

/**
 * Retrieve WP Kernel REST controllers generated for this plugin.
 *
 * @return array<int, object>
 */
function get_kernel_controllers(): array
{
        return [];
}

/**
 * Register WP Kernel REST controllers with WordPress.
 */
function register_kernel_routes(): void
{
        $controllers = get_kernel_controllers();

        foreach ($controllers as $controller) {
                if (!\method_exists($controller, 'register_routes')) {
                        continue;
                }

                $controller->register_routes();
        }
}

/**
 * Attach kernel hooks required for REST registration.
 */
function bootstrap_kernel(): void
{
        \add_action('rest_api_init', __NAMESPACE__ . '\\register_kernel_routes');
}

bootstrap_kernel();
// WPK:END AUTO
