<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources (storage + identity metadata)
 */
namespace Acme\Jobs\Generated\Registration;

// WPK:BEGIN AUTO
final class PersistenceRegistry
{
    public static function get_config(): array
    {
        return ['resources' => ['job' => ['identity' => ['cast' => 'int', 'guards' => ['is_numeric'], 'param' => 'id', 'type' => 'number'], 'storage' => ['meta' => ['external_url' => ['single' => true, 'type' => 'string'], 'location' => ['single' => true, 'type' => 'string'], 'salary_max' => ['single' => true, 'type' => 'number'], 'salary_min' => ['single' => true, 'type' => 'number']], 'mode' => 'wp-post', 'postType' => 'acme_job', 'statuses' => ['closed', 'draft', 'publish'], 'supports' => ['custom-fields', 'editor', 'excerpt', 'title'], 'taxonomies' => ['acme_job_department' => ['hierarchical' => false, 'register' => true, 'taxonomy' => 'acme_job_department'], 'acme_job_location' => ['hierarchical' => true, 'register' => true, 'taxonomy' => 'acme_job_location']]]]]];
    }
}
// WPK:END AUTO
