<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → php/index
 */
namespace Acme\Jobs\Generated;

// WPK:BEGIN AUTO
require_once(dirname(__DIR__, 2) . '/plugin.php');
return ['Acme\Jobs\Generated\Rest\BaseController' => __DIR__ . '/Rest/BaseController.php', 'Acme\Jobs\Generated\Capability\Capability' => __DIR__ . '/Capability/Capability.php', 'Acme\Jobs\Generated\Registration\PersistenceRegistry' => __DIR__ . '/Registration/PersistenceRegistry.php', 'Acme\Jobs\Generated\Rest\JobController' => __DIR__ . '/Rest/JobController.php'];
// WPK:END AUTO
