import fs from 'node:fs';
import path from 'node:path';

describe('wpk-config reference', () => {
	const docPath = path.resolve(
		__dirname,
		'../../docs/reference/wpk-config.md'
	);
	const doc = fs.readFileSync(docPath, 'utf8');

	const REQUIRED_SNIPPETS = [
		'`version`',
		'`namespace`',
		'`schemas`',
		'`resources`',
		'`adapters`',
		'`adapters.php`',
		'`adapters.extensions`',
		'`schemas.<key>.path`',
		'`schemas.<key>.generated.types`',
		'`schemas.<key>.description`',
		'`resources.<key>.name`',
		'`resources.<key>.namespace`',
		'`resources.<key>.schema`',
		'`resources.<key>.storage`',
		'`resources.<key>.identity`',
		'`resources.<key>.routes`',
		'`resources.<key>.capabilities`',
		'`resources.<key>.queryParams`',
		'`resources.<key>.ui`',
		'`resources.<key>.routes.list`',
		'`resources.<key>.routes.get`',
		'`resources.<key>.routes.create`',
		'`resources.<key>.routes.update`',
		'`resources.<key>.routes.remove`',
		'`resources.<key>.routes.*.path`',
		'`resources.<key>.routes.*.method`',
		'`resources.<key>.routes.*.capability`',
		'`resources.<key>.capabilities.<cap>.capability`',
		'`resources.<key>.capabilities.<cap>.appliesTo`',
		'`resources.<key>.capabilities.<cap>.binding`',
		'`resources.<key>.identity.type`',
		'`resources.<key>.identity.param`',
		'`resources.<key>.storage.mode`',
		'`resources.<key>.storage.postType`',
		'`resources.<key>.storage.statuses`',
		'`resources.<key>.storage.supports`',
		'`resources.<key>.storage.meta`',
		'`resources.<key>.storage.taxonomies`',
		'`resources.<key>.storage.taxonomies.*.taxonomy`',
		'`resources.<key>.storage.taxonomies.*.hierarchical`',
		'`resources.<key>.storage.taxonomies.*.register`',
		'`resources.<key>.storage.taxonomy`',
		'`resources.<key>.storage.hierarchical`',
		'`resources.<key>.storage.option`',
		'`resources.<key>.queryParams.<param>.type`',
		'`resources.<key>.queryParams.<param>.enum`',
		'`resources.<key>.queryParams.<param>.optional`',
		'`resources.<key>.queryParams.<param>.description`',
		'`resources.<key>.ui.admin.view`',
		'`resources.<key>.ui.admin.dataviews`',
		'`resources.<key>.ui.admin.dataviews.fields`',
		'`resources.<key>.ui.admin.dataviews.defaultView`',
		'`resources.<key>.ui.admin.dataviews.actions`',
		'`resources.<key>.ui.admin.dataviews.search`',
		'`resources.<key>.ui.admin.dataviews.searchLabel`',
		'`resources.<key>.ui.admin.dataviews.empty`',
		'`resources.<key>.ui.admin.dataviews.perPageSizes`',
		'`resources.<key>.ui.admin.dataviews.defaultLayouts`',
		'`resources.<key>.ui.admin.dataviews.views`',
		'`resources.<key>.ui.admin.dataviews.views[].id`',
		'`resources.<key>.ui.admin.dataviews.views[].label`',
		'`resources.<key>.ui.admin.dataviews.views[].view`',
		'`resources.<key>.ui.admin.dataviews.views[].description`',
		'`resources.<key>.ui.admin.dataviews.views[].isDefault`',
		'`resources.<key>.ui.admin.dataviews.preferencesKey`',
		'`resources.<key>.ui.admin.dataviews.interactivity`',
		'`resources.<key>.ui.admin.dataviews.interactivity.feature`',
		'`resources.<key>.ui.admin.dataviews.screen`',
		'`resources.<key>.ui.admin.dataviews.screen.component`',
		'`resources.<key>.ui.admin.dataviews.screen.route`',
		'`resources.<key>.ui.admin.dataviews.screen.resourceImport`',
		'`resources.<key>.ui.admin.dataviews.screen.resourceSymbol`',
		'`resources.<key>.ui.admin.dataviews.screen.wpkernelImport`',
		'`resources.<key>.ui.admin.dataviews.screen.wpkernelSymbol`',
		'`resources.<key>.ui.admin.dataviews.screen.menu`',
		'`resources.<key>.ui.admin.dataviews.screen.menu.slug`',
		'`resources.<key>.ui.admin.dataviews.screen.menu.title`',
		'`resources.<key>.ui.admin.dataviews.screen.menu.capability`',
		'`resources.<key>.ui.admin.dataviews.screen.menu.parent`',
		'`resources.<key>.ui.admin.dataviews.screen.menu.position`',
	];

	it('documents every config field', () => {
		for (const snippet of REQUIRED_SNIPPETS) {
			expect(doc).toContain(snippet);
		}
	});
});
